[build]
  command = "npm run build"  # ou o comando de build do seu projeto, se houver
  publish = "."

[functions]
  directory = "netlify/functions"  # Esta linha deve apontar para o diretório correto das funções

[build.environment]
  NODE_VERSION = "18"  # Certifique-se de que a versão do Node está configurada corretamente
