[build]
  publish = "."        # publica a raiz da pasta website, que tem seu index.html etc
  command = "echo 'No build script defined' && exit 0"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
