[build]
  publish = "website"
  command = "echo 'No build script defined' && exit 0"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
